### ISSUE TITLE
Sistema de comentários nos posts

### ISSUE THREAD

**Issue by woliveiras** [leobalter/100-coisas-dev#5]
Seria interessante adicionar um sistema de comentários nas postagens?

Assim, quem visualizar nossas listas, pode enviar dicas de como alcançar o objetivo. :)

**Comment by leobalter** [comment]
seria legal. Caminho livre para PRs

**Comment by woliveiras** [comment]
Show de bola.

Vou ver como posso fazer com Disqus. :)

**Comment by teles** [comment]
Cadê, @woliveiras ? :D

**Comment by woliveiras** [comment]
Valeu por me lembrar mano @teles

**Comment by woliveiras** [comment]
Feito ([c93bc5](https://github.com/leobalter/100-coisas-dev/commit/c93bc5fe353c8c15973b10e480c8e4707977e2fc))

cc: @teles
